import { useState, useRef } from 'react'
import axios from 'axios'
import Speedometer from '../components/Speedometer'

export default function SingleAnalysis() {
  const [image, setImage] = useState(null)
  const [preview, setPreview] = useState(null)
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [showModal, setShowModal] = useState(false)
  const fileRef = useRef()

  const handleFile = (file) => {
    if (!file) return
    setImage(file)
    setPreview(URL.createObjectURL(file))
    setResult(null)
    setError(null)
  }

  const handleDrop = (e) => {
    e.preventDefault()
    handleFile(e.dataTransfer.files[0])
  }

  const removeImage = (e) => {
    e.stopPropagation()
    setImage(null)
    setPreview(null)
    setResult(null)
    setError(null)
    fileRef.current.value = ''
  }

  const analyze = async () => {
    if (!image) return
    setLoading(true)
    setError(null)
    try {
      const formData = new FormData()
      formData.append('file', image)
      const res = await axios.post('http://127.0.0.1:8000/analyze', formData)
      setResult(res.data)
    } catch (err) {
      setError('Failed to connect to backend. Make sure the server is running.')
    }
    setLoading(false)
  }

  return (
    <div className="py-10">

      {/* Image Preview Modal */}
      {showModal && preview && (
        <div
          className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-6"
          onClick={() => setShowModal(false)}
        >
          <div className="relative max-w-4xl w-full" onClick={(e) => e.stopPropagation()}>
            <button
              onClick={() => setShowModal(false)}
              className="absolute -top-10 right-0 text-white/60 hover:text-white text-sm font-medium"
            >
              Close
            </button>
            <img
              src={preview}
              alt="full preview"
              className="w-full rounded-2xl object-contain max-h-[80vh]"
            />
          </div>
        </div>
      )}

      {/* Hero */}
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 bg-[#00d4aa]/10 border border-[#00d4aa]/30 rounded-full px-4 py-1.5 text-xs font-semibold text-[#00d4aa] tracking-widest uppercase mb-5">
          <span className="w-1.5 h-1.5 rounded-full bg-[#00d4aa] animate-pulse inline-block" />
          Vision Transformer Model
        </div>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-gray-900 dark:text-white mb-4">
          Is this image <span className="text-[#00d4aa]">real?</span>
        </h1>
        <p className="text-gray-500 dark:text-gray-400 text-base max-w-md mx-auto leading-relaxed">
          Upload any image and our model will detect whether it was captured by a camera or generated by AI.
        </p>
      </div>

      {/* ===== TOP SECTION — Upload + Result ===== */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">

        {/* Upload Panel */}
        <div className="flex flex-col gap-4">
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Upload Image</p>

          <div
            onDrop={handleDrop}
            onDragOver={(e) => e.preventDefault()}
            onClick={() => !preview && fileRef.current.click()}
            className={`relative border-2 border-dashed rounded-2xl p-8 text-center transition-all duration-200 min-h-[220px] flex flex-col items-center justify-center ${
              preview
                ? 'border-[#00d4aa]/40 cursor-default'
                : 'border-gray-200 dark:border-white/10 cursor-pointer hover:border-[#00d4aa] hover:bg-[#00d4aa]/5'
            }`}
          >
            {preview ? (
              <>
                <img
                  src={preview}
                  alt="preview"
                  className="max-h-64 rounded-xl object-contain mx-auto cursor-zoom-in"
                  onClick={() => setShowModal(true)}
                />
                <button
                  onClick={removeImage}
                  className="absolute top-3 right-3 w-7 h-7 rounded-full bg-red-500 hover:bg-red-600 text-white text-xs font-bold flex items-center justify-center transition-colors"
                >
                  x
                </button>
                <p
                  className="text-xs text-gray-400 mt-3 cursor-pointer hover:text-[#00d4aa] transition-colors"
                  onClick={() => setShowModal(true)}
                >
                  Click image to preview full size
                </p>
              </>
            ) : (
              <div className="flex flex-col items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-gray-100 dark:bg-white/5 flex items-center justify-center">
                  <svg className="w-6 h-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
                  </svg>
                </div>
                <p className="text-sm font-medium text-gray-500 dark:text-gray-400">
                  Drag and drop or click to upload
                </p>
                <p className="text-xs text-gray-400">JPG, JPEG, PNG supported</p>
              </div>
            )}
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => handleFile(e.target.files[0])}
            />
          </div>

          {image && (
            <div className="flex flex-wrap gap-2">
              {[
                { label: image.name },
                { label: `${(image.size / 1024).toFixed(1)} KB` },
                { label: image.type.split('/')[1].toUpperCase() },
              ].map((chip, i) => (
                <span key={i} className="text-xs font-medium bg-gray-100 dark:bg-white/5 text-gray-500 dark:text-gray-400 px-3 py-1.5 rounded-full">
                  {chip.label}
                </span>
              ))}
            </div>
          )}

          <button
            onClick={analyze}
            disabled={!image || loading}
            className="w-full py-3.5 rounded-xl font-semibold text-sm tracking-wide transition-all duration-200 disabled:opacity-40 disabled:cursor-not-allowed"
            style={{
              background: image && !loading ? 'linear-gradient(135deg, #00d4aa, #00b894)' : undefined,
              backgroundColor: !image || loading ? '#e5e7eb' : undefined,
              color: image && !loading ? 'white' : '#9ca3af'
            }}
          >
            {loading ? 'Analyzing...' : 'Analyze Image'}
          </button>

          {error && (
            <p className="text-xs text-red-400 text-center">{error}</p>
          )}
        </div>

        {/* Result Panel */}
        <div className="flex flex-col gap-4">
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Detection Result</p>

          {!result && !loading && (
            <div className="border border-gray-100 dark:border-white/10 rounded-2xl p-10 flex flex-col items-center justify-center gap-3 min-h-[300px]">
              <div className="w-12 h-12 rounded-xl bg-gray-100 dark:bg-white/5 flex items-center justify-center">
                <svg className="w-6 h-6 text-gray-300 dark:text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                </svg>
              </div>
              <p className="text-sm font-medium text-gray-400">Upload an image to see results</p>
              <p className="text-xs text-gray-300 dark:text-gray-600">Results will appear here after analysis</p>
            </div>
          )}

          {loading && (
            <div className="border border-gray-100 dark:border-white/10 rounded-2xl p-10 flex flex-col items-center justify-center gap-4 min-h-[300px]">
              <div className="w-10 h-10 rounded-full border-2 border-[#00d4aa] border-t-transparent animate-spin" />
              <p className="text-sm text-gray-400">Running deep scan...</p>
            </div>
          )}

          {result && (
            <div className={`rounded-2xl p-6 border ${
              result.prediction === 'FAKE'
                ? 'bg-red-50 dark:bg-red-950/20 border-red-200 dark:border-red-900/40'
                : result.prediction === 'REAL'
                ? 'bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-900/40'
                : 'bg-gray-50 dark:bg-white/5 border-gray-200 dark:border-white/10'
            }`}>

              <div className="text-center mb-6">
                <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-2">Verdict</p>
                <h2 className={`text-3xl font-bold tracking-tight ${
                  result.prediction === 'FAKE' ? 'text-red-500' :
                  result.prediction === 'REAL' ? 'text-emerald-500' :
                  'text-gray-400'
                }`}>
                  {result.display_text}
                </h2>
              </div>

              <Speedometer value={result.fake_score} />

              <div className="mt-6 grid grid-cols-2 gap-3">
                {[
                  { label: 'AI Generated', value: result.fake_score, color: '#ef4444' },
                  { label: 'Real Image', value: result.real_score, color: '#10b981' },
                  { label: 'Confidence', value: result.confidence, color: '#00d4aa' },
                ].map((item, i) => (
                  <div key={i} className="bg-white/60 dark:bg-white/5 rounded-xl p-3">
                    <p className="text-xs text-gray-400 mb-1">{item.label}</p>
                    <p className="text-lg font-bold" style={{ color: item.color }}>
                      {item.value.toFixed(1)}%
                    </p>
                    <div className="mt-1.5 h-1 rounded-full bg-gray-200 dark:bg-white/10 overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-700"
                        style={{ width: `${item.value}%`, backgroundColor: item.color }}
                      />
                    </div>
                  </div>
                ))}
              </div>

            </div>
          )}
        </div>
      </div>

      {/* ===== BOTTOM SECTION — Image Property Analysis ===== */}
      {/* ===== BOTTOM SECTION — Property Analysis + Heatmap ===== */}
      {result && (
        <div className="flex flex-col gap-6 mt-4">

          {/* Property Analysis */}
          <div className="border border-gray-100 dark:border-white/10 rounded-2xl p-6">
            <div className="mb-6">
              <p className="text-xs font-semibold text-[#00d4aa] uppercase tracking-widest mb-1">Deep Analysis</p>
              <h3 className="text-lg font-bold text-gray-900 dark:text-white">Image Property Breakdown</h3>
              <p className="text-xs text-gray-400 mt-1">Measured directly from image pixels using computer vision</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[
                { label: 'Lighting Consistency', key: 'lighting_consistency', desc: 'Brightness uniformity across regions', aiTrait: 'High = artificial lighting' },
                { label: 'Texture Smoothness', key: 'texture_smoothness', desc: 'Surface detail and natural grain', aiTrait: 'High = unnaturally smooth' },
                { label: 'Edge Sharpness', key: 'edge_sharpness', desc: 'Precision and density of edges', aiTrait: 'High = overly perfect edges' },
                { label: 'Color Distribution', key: 'color_distribution', desc: 'Spread of colors across channels', aiTrait: 'High = artificial uniformity' },
                { label: 'Noise Pattern', key: 'noise_pattern', desc: 'Camera sensor noise presence', aiTrait: 'High = unnaturally clean' },
              ].map((item, i) => {
                const value = result.properties[item.key]
                const color = value > 70 ? '#ef4444' : value > 40 ? '#f59e0b' : '#10b981'
                return (
                  <div key={i} className="bg-gray-50 dark:bg-white/5 rounded-xl p-4 border border-gray-100 dark:border-white/10">
                    <div className="flex items-start justify-between mb-3">
                      <div>
                        <p className="text-sm font-semibold text-gray-800 dark:text-gray-200">{item.label}</p>
                        <p className="text-xs text-gray-400 mt-0.5">{item.desc}</p>
                      </div>
                      <p className="text-xl font-bold ml-2 flex-shrink-0" style={{ color }}>
                        {value.toFixed(1)}%
                      </p>
                    </div>
                    <div className="h-2 rounded-full bg-gray-200 dark:bg-white/10 overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-700"
                        style={{ width: `${value}%`, backgroundColor: color }}
                      />
                    </div>
                    <p className="text-xs text-gray-400 mt-2 font-medium">{item.aiTrait}</p>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Heatmap Section */}
          {result.heatmap && (
            <div className="border border-gray-100 dark:border-white/10 rounded-2xl p-6">
              <div className="mb-6">
                <p className="text-xs font-semibold text-[#00d4aa] uppercase tracking-widest mb-1">Attention Heatmap</p>
                <h3 className="text-lg font-bold text-gray-900 dark:text-white">Where the Model Looked</h3>
                <p className="text-xs text-gray-400 mt-1">
                  Red areas = high model attention. Blue areas = ignored regions. Shows exactly which parts influenced the verdict.
                </p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Original Image */}
                <div>
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-3">Original Image</p>
                  <img
                    src={preview}
                    alt="original"
                    className="w-full rounded-xl object-contain border border-gray-100 dark:border-white/10"
                  />
                </div>
                {/* Heatmap Overlay */}
                <div>
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-3">Attention Map</p>
                  <img
                    src={result.heatmap}
                    alt="heatmap"
                    className="w-full rounded-xl object-contain border border-gray-100 dark:border-white/10"
                  />
                </div>
              </div>
              {/* Color Legend */}
              <div className="mt-4 flex items-center gap-6 justify-center">
                <div className="flex items-center gap-2">
                  <div className="w-4 h-4 rounded-full bg-blue-500" />
                  <p className="text-xs text-gray-400">Low attention</p>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-4 h-4 rounded-full bg-green-500" />
                  <p className="text-xs text-gray-400">Medium attention</p>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-4 h-4 rounded-full bg-red-500" />
                  <p className="text-xs text-gray-400">High attention</p>
                </div>
              </div>
            </div>
          )}

        </div>
      )}

    </div>
  )
}