import { Link } from 'react-router-dom'

export default function Footer() {
  return (
    <footer className="border-t border-gray-200 dark:border-white/10 mt-20">
      <div className="max-w-6xl mx-auto px-6 py-12">

        {/* Top Row */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10 mb-10">

          {/* Brand */}
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 rounded-lg bg-[#00d4aa] flex items-center justify-center">
                <div className="w-3 h-3 rounded-full bg-white" />
              </div>
              <span className="font-bold text-lg tracking-tight text-gray-900 dark:text-white">
                Image<span className="text-[#00d4aa]">Forensic</span>
              </span>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed max-w-xs">
              An AI-powered image authenticity detector. Upload any image and find out with evidence whether it was captured by a real camera or generated by AI.
            </p>

            {/* Accuracy badge */}
            <div className="flex items-center gap-2 mt-5">
              <div className="w-2 h-2 rounded-full bg-[#00d4aa] animate-pulse" />
              <span className="text-xs font-medium text-[#00d4aa]">94.45% Detection Accuracy</span>
            </div>
          </div>

          {/* Navigation */}
          <div>
            <p className="text-xs font-semibold text-gray-900 dark:text-white uppercase tracking-widest mb-4">
              Navigation
            </p>
            <div className="flex flex-col gap-3">
              {[
                { label: 'Analyze Image', path: '/' },
                { label: 'Compare Images', path: '/compare' },
                { label: 'About', path: '/about' },
              ].map((link, i) => (
                <Link
                  key={i}
                  to={link.path}
                  className="text-sm text-gray-500 dark:text-gray-400 hover:text-[#00d4aa] transition-colors duration-200"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          {/* Features */}
          <div>
            <p className="text-xs font-semibold text-gray-900 dark:text-white uppercase tracking-widest mb-4">
              Features
            </p>
            <div className="flex flex-col gap-3">
              {[
                'Pixel-Level Analysis',
                'Attention Heatmap',
                'Property Scores',
                'Side-by-Side Compare',
              ].map((item, i) => (
                <span key={i} className="text-sm text-gray-500 dark:text-gray-400">
                  {item}
                </span>
              ))}
            </div>
          </div>

        </div>

        {/* Divider */}
        <div className="border-t border-gray-200 dark:border-white/10 pt-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-xs text-gray-400">
            © 2025 ImageForensic. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <span className="text-xs text-gray-400">Zero data stored</span>
            <span className="w-1 h-1 rounded-full bg-gray-300 dark:bg-gray-600" />
            <span className="text-xs text-gray-400">No sign-up required</span>
            <span className="w-1 h-1 rounded-full bg-gray-300 dark:bg-gray-600" />
            <span className="text-xs text-gray-400">Privacy first</span>
          </div>
        </div>

      </div>
    </footer>
  )
}